### ISSUE TITLE
Path is not filled correctly

### ISSUE THREAD

**Issue by haan123** [rough-stuff/rough#165]
Hi @pshihn,

Could you please take a look to this issue, when a rectangle path containing 2 hole inside it, the filling looks like screenshot below :(, thanks! 

https://jsfiddle.net/483y5tdo/

```javascript
generator.path(pathData, {
  "stroke": "#000000",
  "fill": "#ced4da",
  "fillStyle": "solid",
  "strokeWidth": 1,
  "roughness": 0,
  "seed": 1067011870,
  "combineNestedSvgPaths": true
})
```
![image](https://user-images.githubusercontent.com/5218341/83093847-71b8dd00-a0ca-11ea-94b8-c8e022966ecf.png)

Thanks!

**Comment by pshihn** [comment]
I'm working on improving algorithm to support this. Sorry for the late response. Infant baby = neglect open source :(

**Comment by pshihn** [comment]
Fixed by https://github.com/rough-stuff/rough/pull/195 Releases as `v4.5.0` on npm.
