### ISSUE TITLE
Filling a path is always done with non-zero fill-rule

### ISSUE THREAD

**Issue by jesperkc** [rough-stuff/rough#167]
This problem still exists when using https://unpkg.com/roughjs@4.3.1/bundled/rough.js

https://jsfiddle.net/rwpgx2t0/

-------

Using a different path (taken from the SVG spec), winding direction indeed makes a difference, indicating non-zero-ness:

fill-rule=evenodd
![image](https://user-images.githubusercontent.com/1692688/73616756-c2866080-4617-11ea-85df-2e86b50aff93.png)
![image](https://user-images.githubusercontent.com/1692688/73616760-c9ad6e80-4617-11ea-93ae-d26d389fda08.png)

fill-rule=nonzero
![image](https://user-images.githubusercontent.com/1692688/73616766-d4680380-4617-11ea-8197-3315d1f1c9c0.png)
![image](https://user-images.githubusercontent.com/1692688/73616768-daf67b00-4617-11ea-808e-b4de6f69adcc.png)

_Originally posted by @ygra in https://github.com/pshihn/rough/issues/131#issuecomment-581187205_

**Comment by fskpf** [comment]
The behavior is also dependant on the `combineNestedSvgPaths` in combination with the `fillStyle`. For example test the fill-rule [evenodd example from the SVG spec](https://www.w3.org/TR/SVG11/images/painting/fillrule-evenodd.svg) on https://fskpf.github.io/ (where `combineNestedSvgPaths` is enabled) and cycle through the fill-styles:

From top to bottom (same input): Original SVG // fillStyle hachure // fillStyle solid
![fillrule-evenodd](https://user-images.githubusercontent.com/17721806/85218538-c1be5300-b39b-11ea-9466-a3d70f127c6e.png)

Is `combineNestedSvgPaths` intended to address this problem, e.g. setting it dependant on the nested path direction and its `fill-rule`, so basically switch between "fill or don't fill nested paths"? 
Though I guess this would not really work for cases where the path contains nested subpaths with both directions (with the surrounding shape's direction and against it), e.g.
```
<svg viewBox="-10 -10 110 110" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="nonzero" stroke="blue" d="
    M10,0  h90 v90 h-90 z
    M30,20 v20 h50 v-20 z 	
    M30,60 h50 v20 h-50 z"/>
</svg>
```
![image](https://user-images.githubusercontent.com/17721806/85219129-54adbc00-b3a1-11ea-86cb-dea52a1c0017.png)


Also, fill-style solid needs to consider this as well.

**Comment by pshihn** [comment]
Although I have not done any work on winding direction yet, most issues with nested paths should be fixed now:
Fixed by https://github.com/rough-stuff/rough/pull/195 Releases as `v4.5.0` on npm.

**Comment by jesperkc** [comment]
Can confirm it works now
