### ISSUE TITLE
Draw text on canvas using roughjs

### ISSUE THREAD

**Issue by adarsh45** [rough-stuff/rough#172]
There is no mention of how we can draw Text similar to drawing shapes on a Canvas!
Is there any way to do so?

**Comment by pshihn** [comment]
Nothin in RoughJS directly, but you can use canvas element yourself. Rough rendering and your own canvas code can coexist. 
See: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Drawing_text
