### ISSUE TITLE
How to clear the canvas?

### ISSUE THREAD

**Issue by zzkung** [rough-stuff/rough#175]
![image](https://user-images.githubusercontent.com/42987595/108882129-03944d00-763f-11eb-9a38-6533e593cbee.png)
![image](https://user-images.githubusercontent.com/42987595/108882232-1f97ee80-763f-11eb-95ea-0e68d6f97dce.png)

I want to clear the rectangle drawn before, but it says ‘rc.clearRect is not a function’

**Comment by zzkung** [comment]
![image](https://user-images.githubusercontent.com/42987595/108933059-6e687700-7685-11eb-97e3-a445265c7a89.png)
Probably to use 'rc.ctx'?

**Comment by pshihn** [comment]
`rc.ctx` is not a documented property so you should not rely on that. 

you have the reference to the canvasElement and can get the context yourself. In your code, you have the `canvasEle`
```javascript
const canvasEle = document.getElementById('canvas');
const ctx = canvasEle.getContext('2d');
ctx.clearRect(.....)
```
