### ISSUE TITLE
Setting stroke to "none" has no effect on canvas

### ISSUE THREAD

**Issue by jwoLondon** [rough-stuff/rough#177]
Is there a way to stop outer stroke drawing on canvas? Setting `stroke:"none"` works for SVG but not for canvas. I realise one can set `stroke: "rgba(0,0,0,0)"`, but would be good to have a more performant approach and one that is consistent between SVG and Canvas contexts.

**Comment by pshihn** [comment]
If it doesn't do that on canvas, then it's definitely a bug. Let me take a look.

**Comment by jwoLondon** [comment]
Here's a minimal reproducible example via Observable:

https://observablehq.com/d/e7de66607b365674

**Comment by pshihn** [comment]
Ahh it got fixed in v4.0 Your example uses 3.0
Here's a fork with the latest version: https://observablehq.com/@preetster/rough-strokes

**Comment by jwoLondon** [comment]
Ah, thanks. I didn't realise there was a V4. Sorry for wasting your time.

**Comment by pshihn** [comment]
no problem at all!
