### ISSUE TITLE
'Leaking' hachures in nested polygons

### ISSUE THREAD

**Issue by jwoLondon** [rough-stuff/rough#183]
Likely related to #165 and #167: For nested holes and islands when setting `combineNestedSvgPaths: true`, I see leaking of the hachures at the `moveTo` vertex of each sub-path.

See this [interactive minimal reproducible example](https://observablehq.com/d/c7572074fb4bd6d5)

![leakingHachures](https://user-images.githubusercontent.com/1846999/119233125-5e92ee80-bb1f-11eb-911c-683e2f8a43a7.jpg)

As an aside, I only recently discovered the `combineNestedSvgPaths` option by looking at the source code. I couldn't see it in the [API documentation](https://github.com/rough-stuff/rough/wiki). I may have missed it, but it would be nice to have the option of setting the type of fill rule (non-zero; even-odd; always).

**Comment by fskpf** [comment]
Any fill style is affected.

I'd love to see a fix for this. Currently, `combineNestedSvgPath` cannot really be used due to this.

**Comment by pshihn** [comment]
I'm working on improving algorithm to support this. Sorry for the late response. Infant baby = neglect open source :(

**Comment by pshihn** [comment]
I have it working! https://twitter.com/preetster/status/1457242142481338368?s=20 
Will merge and release after some more testing

**Comment by pshihn** [comment]
Fixed by https://github.com/rough-stuff/rough/pull/195 Releases as `v4.5.0` on npm. 
Note roughjs only does even-odd fills. The `combineNestedSvgPaths` was a stop gap hack, which is why it was not documented. That property is ignored now.
