### ISSUE TITLE
ellipse with 0 roughness is still irregular

### ISSUE THREAD

**Issue by dwelle** [rough-stuff/rough#185]
![image](https://user-images.githubusercontent.com/5153846/128679606-676c8dd8-65a6-4b98-beed-08f86bdff452.png)

options:

```
curveFitting: 1
disableMultiStroke: true
preserveVertices: false
roughness: 0
strokeWidth: 1
```

`disableMultiStroke` can be true/false, doesn't make a difference.

Reported on excalidraw https://github.com/excalidraw/excalidraw/issues/3906

**Comment by vjeux** [comment]
cc @pshihn
