### ISSUE TITLE
"Dots" fill looks weird when units are scaled up

### ISSUE THREAD

**Issue by notwaldorf** [rough-stuff/rough#193]
Hiya!

I'm trying to use `rough.js` with [`canvas-sketch`](https://github.com/mattdesl/canvas-sketch); the only part of this that matters is that `canvas-sketch` lets me use `inches` as the canvas unit, rather than pixels (and it does the  inches-> pixels conversion behind the scenes). For most options this is fine; for ex this is a hashed rectangle of 5x5 inches,
```
const rect = rc.rectangle(1, 1, 5, 5, {
      fill: 'black',
      fillWeight: 0.05, 
      hachureGap: 0.5,
      roughness:0.1,
    });
```
And it looks about what you'd expect (if maybe with slightly wider lines than expected):
<img width="392" alt="Screen Shot 2021-11-04 at 12 50 42 PM" src="https://user-images.githubusercontent.com/1369170/140410002-110d0afe-83a3-4308-8443-c55d8ab588db.png">

When I switch the fill to "dots" however, the dots go really wild:
<img width="401" alt="Screen Shot 2021-11-04 at 12 51 47 PM" src="https://user-images.githubusercontent.com/1369170/140410088-b4df6d5f-2e5c-421d-af96-215c5318542f.png">

I assume this is happening because there's some internal math that assumes pixels, but before I go digging where to fix that locally, I was wondering if you had any advice of where to look? Or any hacks to just scale the dots down more (that isn't "stop using inches :sob:")? The `fillWeight` seems to be getting ignored in my case, or somehow scaled in the library maybe? (0.05 inches should be a very small radius, but if i crank up the hachure gap to 3 inches soIid just get fewer dots, it still looks wrong and not like a teensy circle:
<img width="355" alt="Screen Shot 2021-11-04 at 12 53 37 PM" src="https://user-images.githubusercontent.com/1369170/140410344-4f2c8b5b-5bef-453d-9439-90af10fc9806.png">

I'm sorry for the edge case! Thanks in advance! 🙏

**Comment by notwaldorf** [comment]
Ah, hmm, I think it might be this line: https://github.com/rough-stuff/rough/blob/master/src/fillers/dot-filler.ts#L34, which is bad (for me) because i can see why you'd want a ceiling there 😂

**Comment by pshihn** [comment]
I was looking at it. and I realized there's just a flaw in the code. The `ceil` actually is alright there. 
I am overriding the roughness in this case: https://github.com/rough-stuff/rough/blob/master/src/fillers/dot-filler.ts#L14 which is just hacky

**Comment by pshihn** [comment]
@notwaldorf I just published a patch (https://github.com/rough-stuff/rough/pull/194) release `v4.4.5`.
Let me know if it works for you.

**Comment by pshihn** [comment]
Here's a sample with the latest build: https://codepen.io/shihn/pen/PoKQjQE

**Comment by notwaldorf** [comment]
Ahhhh this is amazing! I will give it a try today, thank you so much! 🥰

**Comment by notwaldorf** [comment]
(In the meantime I need to thank you for the code in geometry.ts, it has been a *life saver*)
