### ISSUE TITLE
0-roughness ellipse not closed in specific cases

### ISSUE THREAD

**Issue by dwelle** [rough-stuff/rough#197]
![image](https://user-images.githubusercontent.com/5153846/144254474-5c1bea9a-cd59-4efa-b19f-d5cecac037fb.png)

https://excalidraw.com/#json=R1JU7RsS5B7Pdo9ZdyS0S,_KvML889O3uvvh-NpJV7KQ

I believe it's related to https://github.com/rough-stuff/rough/pull/189, because it started happening on excalidraw after we landed the fix.

You can copy/paste the ellipse into these previews:

The commit it starts to first reproduce on: https://excalidraw-8tfjr1cim-excalidraw.vercel.app/ (https://github.com/excalidraw/excalidraw/pull/4194)
Commit before: https://excalidraw-8d0rzxm4n-excalidraw.vercel.app/ (doesn't reproduce)

Reproduces across browsers (Chrome 96, FF, Safari).

**Comment by pshihn** [comment]
This is weird. I see the issue in the link you share but every new ellipse I draw, it draws properly. 
There's definitely a bug. I'll check it out.

**Comment by pshihn** [comment]
fix released in v4.5.1

**Comment by dwelle** [comment]
Thanks for the quick fix! ❤️
