### ISSUE TITLE
Ellipse not completely filled

### ISSUE THREAD

**Issue by anudeepreddy** [rough-stuff/rough#199]
When creating an ellipse with roughness 0 and default fill style doesn't fully fill the ellipse.
```js
rc.ellipse(100, 50, 150, 80, {
      fill: 'blue',
      roughness: 0
    });
```
![image](https://user-images.githubusercontent.com/6022231/145518439-26fb1791-6927-4548-a8b1-43acee5b63b6.png)

**Comment by pshihn** [comment]
Sorry about that. I broke it as part of another fix. 
Fixed https://github.com/rough-stuff/rough/pull/200
Fix available in v4.5.2
